#   __ _____                      _ _         
#  / _/ ____|                    (_) |        
# | || (___   ___  ___ _   _ _ __ _| |_ _   _ 
# |  _\___ \ / _ \/ __| | | | '__| | __| | | |
# | | ____) |  __/ (__| |_| | |  | | |_| |_| |
# |_||_____/ \___|\___|\__,_|_|  |_|\__|\__, |
#                                        __/ |
#                                       |___/ 
#                                             

Ayarlar:
  Kod: 1234
  Gereken İzin: fsecurity.join
  Admin İzin: fsecurity.admin
  Kodu Girme Süresi Kaç Saniye Olsun: 60
  Kodu Yanlış Girince Atılsın Mı: false
  Ses Efektleri Kullanılsın Mı: true
  Title Mesajları Kullanılsın Mı: true

Title Mesajlar:
  Lütfen Kodu Girin:
    Title: "&6Güvenlik Kodunu Girin"
    Subtitle: "&e/doğrula <kod>"
  Doğrulama Başarılı:
    Title: "&2&l✔"
    Subtitle: "&aDoğrulama Başarılı"
  Girilen Kod Yanlış:
    Title: "&4&l✖"
    Subtitle: "&cGirilen Kod Yanlış"
  Yetkin Yok:
    Title: "&4&l✖"
    Subtitle: "&cYetkiniz Yok" 
   
Mesajlar:
  Prefix: "&6fSecurity &8» "
  Doğrulama Başarılı: "&aDoğrulama Başarılı."
  Girilen Kod Yanlış: "&cGirilen Kod Yanlış."
  Yenileme Başarılı: "&afSecurity &7Başarıyla Yenilendi."
  Lütfen Kodu Girin: "&7Lütfen Güvenlik Kodunu Girin: &a/doğrula <kod>"
  Doğrulama Zaten Başarılı: "&7Güvenlik Kodu Zaten Doğrulanmış."
  Doğrulama Zaman Aşımına Uğradı: "&cDoğrulama Zaman Aşımına Uğradığı Için Atıldınız."
  Yetkin Yok: "&7Bu Komutu Kullanmak Için Gereken Yetkiye Sahip Değilsiniz."
  Kodu Doğrulamadan Konuşamazsın: "&7Güvenlik Kodunu Girmeden Sohbet Edemezsiniz."
  Kodu Doğrulamadan Komut Kullanamazsın: "&7Güvenlik Kodunu Girmeden Komut Kullanamazsınız."
  Kodu Doğrulamadan Hareket Edemezsin: "&7Güvenlik Kodunu Girmeden Hareket Edemezsiniz."